name: felexo
description: A library of wallpapers directly from Pexels

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0002+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission:
    git:
      url: https://github.com/kamlesh9070/permission
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.3
  complimentary_colors: ^1.0.3
  dio: ^4.0.0
  expandable_bottom_sheet: ^0.2.1+1
  google_mobile_ads: ^0.12.1
  firebase_auth: ^1.0.1
  firebase_auth_web: ^1.0.3
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.2
  flutter_cache_manager: ^3.0.1
  flutter_parallax: ^0.1.2
  google_sign_in: ^5.0.1
  http: ^0.13.1
  image_gallery_saver: ^1.6.9
  path: ^1.7.0
  path_provider: ^2.0.0
  provider: ^4.3.2+2
  random_string: ^2.1.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  wallpaper_manager: ^1.0.10
  bordered_text: ^1.0.1
  lottie: ^1.0.1
  package_info: ^2.0.0
  md2_tab_indicator: ^1.0.2  
  shimmer_animation: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: Theme Black
      fonts:
        - asset: assets/fonts/Proxima Nova Black.otf

    - family: Theme Bold
      fonts:
        - asset: assets/fonts/Proxima Nova Bold.otf

    - family: Theme Regular
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
