name: felexo
description: A library of wallpapers directly from Pexels

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission:
    git:
      url: https://github.com/kamlesh9070/permission
  auto_size_text: ^2.1.0
  bordered_text: ^1.0.0
  cached_network_image: ^2.2.0+1
  cloud_firestore: ^0.14.3+1
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  expandable_bottom_sheet: ^0.2.1+1
  firebase_admob: ^0.10.2
  firebase_auth: ^0.18.3+1
  firebase_auth_web: ^0.3.2+1
  firebase_core: ^0.5.2+1
  firebase_core_web: ^0.2.1+1
  flutter_auth_buttons: ^0.8.0
  flutter_cache_manager: ^1.4.1
  flutter_group_sliver: ^0.0.2
  flutter_icons: ^1.1.0
  flutter_native_splash: ^0.1.9
  flutter_parallax: ^0.1.2
  google_sign_in: ^4.5.6
  http: ^0.12.2
  image_gallery_saver: ^1.5.0
  lottie: ^0.6.0
  package_info: ^0.4.3+2
  path: ^1.7.0
  path_provider: ^1.6.11
  shared_preferences: ^0.5.12+4
  provider: ^4.3.2+2
  random_string: ^2.1.0
  url_launcher: ^5.5.0
  wallpaper_manager: ^1.0.10
  floating_bottom_navigation_bar: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:

    - family: Circular Black
      fonts:
        - asset: assets/fonts/Circular Std Black.ttf

    - family: Circular Bold
      fonts:
        - asset: assets/fonts/Circular Std Bold.ttf
