name: felexo
description: A library of wallpapers directly from Pexels

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.0001+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  permission:
    git:
      url: https://github.com/kamlesh9070/permission
  auto_size_text: ^2.1.0
  bordered_text: ^1.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^1.0.3
  complimentary_colors: ^1.0.3
  cupertino_icons: ^0.1.3
  dio: ^4.0.0
  english_words: ^4.0.0
  expandable_bottom_sheet: ^0.2.1+1
  # firebase_admob: ^0.10.2
  google_mobile_ads: ^0.12.1
  # firebase_admob_rewarded_video: ^0.0.2
  firebase_auth: ^1.0.1
  firebase_auth_web: ^1.0.3
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.2
  floating_bottom_navigation_bar: ^1.4.1
  flutter_auth_buttons: ^0.8.0
  flutter_cache_manager: ^3.0.1
  flutter_group_sliver: ^0.0.2
  flutter_icons: ^1.1.0
  flutter_parallax: ^0.1.2
  google_sign_in: ^5.0.1
  http: ^0.13.1
  image_gallery_saver: ^1.5.0
  lazy_load_scrollview: ^1.3.0
  lottie: ^1.0.1
  package_info: ^0.4.3+2
  path: ^1.7.0
  path_provider: ^2.0.0
  provider: ^4.3.2+2
  random_string: ^2.1.0
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.3
  wallpaper_manager: ^1.0.10
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Theme Black
      fonts:
        - asset: assets/fonts/Proxima Nova Black.otf

    - family: Theme Bold
      fonts:
        - asset: assets/fonts/Proxima Nova Bold.otf

    - family: Theme Regular
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
